name: Deploy gcloud

on: push

jobs: 
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        deliverables: app.yaml
        version: v1
        credentials: ${{ secrets.GCLOUD_CREDENTIALS }}

    - name: Test deploy works
      run: curl "${{ steps.deploy.outputs.url }}"