name: Testing CI

on:
  push:
    branches: ["main", "develop", "feature-issue#81"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 19.7.0
        uses: actions/setup-node@v3
        with:
          node-version: 19.7.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Start server and run tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run start
          env: |
            CYPRESS_baseUrl=http://localhost:3000
            CYPRESS_backendUrl=https://firee.pythonanywhere.com/
          wait-on: |
            https://firee.pythonanywhere.com/
            http://localhost:3000
          test-command: npm run test
