name: Tests CI
on:
  push:
    branches: ["main", "develop", "feature-issue#81"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [19]
    name: E2E on Node v${{ matrix.node }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v

      - name: Checkout
        uses: actions/checkout@v3

      - name: Wait for React app to start
        uses: kamranahmedse/wait-for-localhost-action@v0.2.0
        with:
          host: localhost
          port: 3000
          timeout: 60

      - name: Wait for PythonAnywhere app to start
        uses: agauniyal/wait-for-url@v1.2.0
        with:
          url: https://firee.pythonanywhere.com/
          timeout: 60

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          tag: node-${{ matrix.node }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
